
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (1,'DATA ENTRY EXPERT',10000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (2,'ASSISTANT PROGRAMMER',15000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (3,'SENIOR PROGRAMMER',20000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (4,'JUNIOR SOFTWARE ENGINEER',25000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (5,'SENIOR SOFTWARE ENGINEER',30000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (6,'HARDWARE MECHANIC',10000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (7,'JUNIOR HARDWARE ENGINEER',20000);
INSERT INTO JOBS(JOB_ID,JOB_TITLE,BASE_SALARY) VALUES (8,'SENIOR HARDWARE ENGINEER',30000);



INSERT INTO LOCATIONS(LOCATION_ID,POSTAL_CODE,STREET_ADDRESS,CITY,COUNTRY) VALUES (1,9421,'MIRPUR-10','DHAKA','BANGLADESH');
INSERT INTO LOCATIONS(LOCATION_ID,POSTAL_CODE,STREET_ADDRESS,CITY,COUNTRY) VALUES (2,6421,'POTENGA','CHITTAGONG','BANGLADESH');
INSERT INTO LOCATIONS(LOCATION_ID,POSTAL_CODE,STREET_ADDRESS,CITY,COUNTRY) VALUES (3,3421,'DAKBANGLA','KHULNA','BANGLADESH');


INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) VALUES (1,'SOFTWARE DEPARTMENT',1);
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) VALUES (2,'HARDWARE DEPARTMENT',2);