CREATE OR REPLACE FUNCTION TOTAL_SALARY RETURN NUMBER IS
   TOT_SAL JOBS.BASE_SALARY%type;
BEGIN
  IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;  

  SELECT SUM(J.BASE_SALARY) INTO TOT_SAL
  FROM EMPLOYEE E JOIN JOBS J ON E.JOB_ID = J.JOB_ID;
   RETURN TOT_SAL;
END;
/

SET SERVEROUTPUT ON
BEGIN
dbms_output.put_line('Total Salary: ' || TOTAL_SALARY);
END;
/

CREATE OR REPLACE FUNCTION AVERAGE_SALARY RETURN NUMBER IS
   AVG_SAL JOBS.BASE_SALARY%type;
BEGIN
   IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;

  SELECT AVG(J.BASE_SALARY) INTO AVG_SAL
  FROM EMPLOYEE E JOIN JOBS J ON E.JOB_ID = J.JOB_ID;
   RETURN AVG_SAL;
END;
/



SET SERVEROUTPUT ON
BEGIN
dbms_output.put_line('Average Salary: ' || AVERAGE_SALARY);
END;
/



CREATE OR REPLACE FUNCTION SOFT_EM RETURN NUMBER IS
EM_NO NUMBER(5);
BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;

SELECT COUNT(*) INTO EM_NO FROM (SELECT JOB_ID FROM EMPLOYEE WHERE JOB_ID<=5);
RETURN EM_NO;
END;
/

BEGIN
DBMS_OUTPUT.PUT_LINE('TOTAL NO OF EMPLOYEE IN SOFTWARE DEPARTMENT : ' || SOFT_EM);
END;
/

CREATE OR REPLACE FUNCTION HARD_EM RETURN NUMBER IS
EM_NO NUMBER(5);
BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;

SELECT COUNT(*) INTO EM_NO FROM (SELECT JOB_ID FROM EMPLOYEE WHERE JOB_ID>5);
RETURN EM_NO;
END;
/



BEGIN
DBMS_OUTPUT.PUT_LINE('TOTAL NO OF EMPLOYEE IN HARDWARE DEPARTMENT : ' || HARD_EM);
END;
/
