
DECLARE
NUM GLOBAL.MY_VAR%TYPE;

BEGIN
	
NUM:=&ADMIN_PASSWORD;
GLOBAL.MY_VAR:=NUM;

IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');

ELSE DBMS_OUTPUT.PUT_LINE('SUCCESSFULLY LOGGED IN');
END IF;

END;
/