DECLARE
V_EMAIL EMPLOYEE.EMAIL%TYPE;
V_EID EMPLOYEE.EMPLOYEE_ID%TYPE;
VAR VARCHAR(10);

BEGIN

--DBMS_OUTPUT.PUT_LINE('GIVE THE ID NO OF THE EMPLOYEE' || CHR(10) );

V_EID:=&EMPLOYEE_ID;

SAVEPOINT SUS;
SELECT EMAIL INTO V_EMAIL FROM EMPLOYEE WHERE EMPLOYEE_ID = V_EID;
DELETE FROM CONTACT WHERE EMAIL=V_EMAIL;

DBMS_OUTPUT.PUT_LINE('ARE YOU SURE TO SUSPEND THE EMPLOYEE (Y/N) ?' || CHR(10) );

VAR:='&VAR';

IF VAR='Y' THEN DBMS_OUTPUT.PUT_LINE(CHR(10) || 'SUSPENSION SUCCESSFULL '  || CHR(10));
ELSE ROLLBACK TO  SUS; DBMS_OUTPUT.PUT_LINE('SUSPENSION CANCELLED' || CHR(10));
END IF;
 

END ;
/
