
CREATE OR REPLACE TRIGGER CHECK_EMPLOYEE BEFORE UPDATE OR DELETE  ON EMPLOYEE

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;



END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_CONTACT BEFORE INSERT OR UPDATE OR DELETE  ON CONTACT

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;



END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_JOBS BEFORE INSERT OR UPDATE OR DELETE  ON JOBS

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;



END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_LOCATIONS BEFORE INSERT OR UPDATE OR DELETE  ON LOCATIONS

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;



END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_DEPARTMENTS BEFORE INSERT OR UPDATE OR DELETE  ON DEPARTMENTS

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;


END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_JOB_HISTORY BEFORE INSERT OR UPDATE OR DELETE  ON JOB_HISTORY

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;


END;
/
SHOW ERRORS;

CREATE OR REPLACE TRIGGER CHECK_ACCOUNT BEFORE INSERT OR UPDATE OR DELETE  ON ACCOUNT

BEGIN
--DBMS_OUTPUT.PUT_LINE('TRIGGERING');
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;
END;
/

SHOW ERRORS;


CREATE OR REPLACE TRIGGER CHECK_EMPLOYEE_ID  
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW

BEGIN
IF GLOBAL.MY_VAR!=ADMIN.MY_VAR THEN 
 RAISE_APPLICATION_ERROR(-20000,'YOU DONOT HAVE ACCESS TO THE DATA');
END IF;

  SELECT ID_SEQ.NEXTVAL
  INTO   :new.EMPLOYEE_ID
  FROM   dual;
END;
/



